name: pipeline

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  workflow_dispatch: { }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - run: ./gradlew clean -x test build -Pvaadin.productionMode=true

      - name: archive production artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: ulich/crm:latest,ulich/crm:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
